version: 2

models:
  - name: customers
    description: Each record is a customer
    columns:
      - name: customer_id
        description: Primary Key
        tests:
          - unique
          - not_null
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: last_name
        description: Testing if the final model inherit the field documentation.

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
